# This workflow uploads release files from the build workflow to another repository

name: Upload Release Files

on:
  workflow_run:
    workflows: [".NET 4.8.1 CI"]  # Name of the build workflow
    types:
      - completed

jobs:
  upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if the previous workflow was successful
    runs-on: ubuntu-latest

    steps:
      - name: Download Release Files
        uses: actions/download-artifact@v3
        with:
          name: Release Files  # Name of the artifact to download

      - name: Upload to Release in Another Repo
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v1.0.0'  # Specify your release tag
          files: |
            Release Files/**  # Path to the downloaded release files
          repository: 'JicoDotNet/Full-Inventory-by-Asp-Net-Azure-Build'  # Replace with your organization and target repo name
        env:
          GITHUB_TOKEN: ${{ secrets.Token_Github }}
